spring:
  application:
    name: pos-orders
  main:
    allow-circular-references: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      function:
        autodetect: false
      bindings:
        order-out-0:
          binder: rabbit
          destination: orderExchange
          group: default
server:
  port: 8810
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
