spring:
  application:
    name: pos-delivery
  main:
    allow-circular-references: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: order
    stream:
      bindings:
        order-in-0:
          binder: rabbit
          destination: orderExchange
          group: default
server:
  port: 10919
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
